name: questions
description: Documentation for the Question Schemas
url: "https://eosdg.github.io"
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled:     true
  collections: true
